import {
  rentalCar1,
  rentalCar2,
  recommendedCar1,
  recommendedCar2,
  recommendedCar3,
  recommendedCar4,
  recommendedCar5,
  recommendedCar6,
  recommendedCar7,
  recommendedCar8,
  PopularCar1,
  PopularCar2,
  PopularCar3,
  PopularCar4,
} from "../assets/images";
import {
  FillHeart,
  TransparentHeart,
  Engine,
  SittingCapacity,
  GasStation,
} from "../assets/icons";
export const servicesData = [
  {
    heading: "The Best Platform for Car Rental",
    text: "Ease of doing a car rental safely and reliably. Of course at a low price.",
    imgURL: rentalCar1,
    btnBg: "bg-[#3563E9]",
    bgURL: "bg-[url('../src/assets/icons/Add1.svg')]",
    btnBg: "bg-[#3563E9]",
  },
  {
    heading: "Easy way to rent a car at a low price",
    text: "Providing cheap car rental services and safe and comfortable facilities.",
    imgURL: rentalCar2,
    btnBg: "bg-[#54A6FF]",
    bgURL: "bg-[url('../src/assets/icons/Add2.svg')]",
    btnBg: "bg-[#54A6FF]",
  },
];
export const popularCars = [
  {
    name: "Koenigsegg",
    type: "Sport",
    rating: FillHeart,
    imgURL: PopularCar1,
    fuel: GasStation,
    fuelCapacity: "90L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "2 People",
    price: "$99.00/",
    time: "day",
  },
  {
    name: "Nissan GT - R",
    type: "Sport",
    rating: TransparentHeart,
    imgURL: PopularCar2,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "2 People",
    price: "$80.00/",
    time: "day",
    oldPrice: "$100.00",
  },
  {
    name: "Rolls - Royce",
    type: "Sedan",
    rating: FillHeart,
    imgURL: PopularCar3,
    fuel: GasStation,
    fuelCapacity: "70L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "4 People",
    price: "$96.00/",
    time: "day",
  },
  {
    name: "Nissan GT - R",
    type: "Sport",
    rating: TransparentHeart,
    imgURL: PopularCar4,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "2 People",
    price: "$80.00/",
    time: "day",
    oldPrice: "$100.00",
  },
  {
    name: "Koenigsegg",
    type: "Sport",
    rating: FillHeart,
    imgURL: PopularCar1,
    fuel: GasStation,
    fuelCapacity: "90L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "2 People",
    price: "$99.00/",
    time: "day",
  },
  {
    name: "Nissan GT - R",
    type: "Sport",
    rating: TransparentHeart,
    imgURL: PopularCar2,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "2 People",
    price: "$80.00/",
    time: "day",
    oldPrice: "$100.00",
  },
  {
    name: "Rolls - Royce",
    type: "Sedan",
    rating: FillHeart,
    imgURL: PopularCar3,
    fuel: GasStation,
    fuelCapacity: "70L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "4 People",
    price: "$96.00/",
    time: "day",
  },
  {
    name: "Nissan GT - R",
    type: "Sport",
    rating: TransparentHeart,
    imgURL: PopularCar4,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "2 People",
    price: "$80.00/",
    time: "day",
    oldPrice: "$100.00",
  },
];
export const recommendedCars = [
  {
    name: "All New Rush",
    type: "SUV",
    rating: TransparentHeart,
    imgURL: recommendedCar1,
    fuel: GasStation,
    fuelCapacity: "70L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "6 People",
    price: "$72.00/",
    time: "day",
    oldPrice: "$80.00 ",
  },
  {
    name: "CR  - V",
    type: "SUV",
    rating: FillHeart,
    imgURL: recommendedCar2,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "6 People",
    price: "$80.00/",
    time: "day",
  },
  {
    name: "All New Terios",
    type: "SUV",
    rating: TransparentHeart,
    imgURL: recommendedCar3,
    fuel: GasStation,
    fuelCapacity: "90L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "6 People",
    price: "$74.00/",
    time: "day",
  },
  {
    name: "CR  - V",
    type: "SUV",
    rating: FillHeart,
    imgURL: recommendedCar4,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "6 People",
    price: "$80.00/",
    time: "day",
  },
  {
    name: "MG ZX Exclusice",
    type: "Hatchback",
    rating: FillHeart,
    imgURL: recommendedCar5,
    fuel: GasStation,
    fuelCapacity: "70L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "4 People",
    price: "$76.00/",
    time: "day",
    oldPrice: "$80.00",
  },
  {
    name: "New MG ZS",
    type: "SUV",
    rating: TransparentHeart,
    imgURL: recommendedCar6,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "6 People",
    price: "$80.00/",
    time: "day",
  },
  {
    name: "MG ZX Excite",
    type: "Hatchback",
    rating: FillHeart,
    imgURL: recommendedCar7,
    fuel: GasStation,
    fuelCapacity: "90L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "4 People",
    price: "$74.00/",
    time: "day",
  },
  {
    name: "New MG ZS",
    type: "SUV",
    rating: TransparentHeart,
    imgURL: recommendedCar8,
    fuel: GasStation,
    fuelCapacity: "80L",
    engineURL: Engine,
    engineType: "Manual",
    sittingCapacityURL: SittingCapacity,
    sittingCapacity: "6 People",
    price: "$80.00/",
    time: "day",
  },
];
export const footerLinks = [
  {
    title: "About",
    links: [
      { name: "How it works", link: "/" },
      { name: "Featured", link: "/" },
      { name: "Partnership", link: "/" },
      { name: "Business Relation", link: "/" },
    ],
  },
  {
    title: "Community",
    links: [
      { name: "Events", link: "/" },
      { name: "Blog", link: "/" },
      { name: "Podcast", link: "/" },
      { name: "Invite a friend", link: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { name: "Discord", link: "/" },
      { name: "Instagram", link: "/" },
      { name: "Twitter", link: "/" },
      { name: "Facebook", link: "/" },
    ],
  },
];
export const policy = [
  { name: "Privacy & Policy ", link: "/" },
  { name: "Terms & Condition", link: "/" },
];
